// playground/stimulus/assets/react/controllers/App.tsx
import { useState } from 'react'
import reactLogo from '~/images/logo-react.svg'
import viteLogo from '~/images/logo-vite.svg'
import './App.scss'

function App(props) {
  const [count, setCount] = useState(0)

  return (
    <div className="react-app">
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" width="202.25" height="200" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" width="215" height="152" />
        </a>
      </div>
      <h1>Hello { props.name }</h1>
      <div>
        <div>
          <button className="react-button" onClick={() => setCount((count) => count + 1)}>
            count is {count}
          </button>
        </div>
        <p>
          <code>assets/react/controllers/App.jsx</code>
        </p>
        <p>
          Edit component and save to test HMR
        </p>
      </div>
      </div>
  )
}

export default App

// playground/stimulus/assets/svelte/controllers/App.svelte
<script>
  import svelteLogo from "~/images/logo-svelte.svg";
  import viteLogo from "~/images/logo-vite.svg";
  import Counter from "../components/Counter.svelte";
  export let name;

  import "./app.scss";
</script>

<main class="svelte-app">
  <div>
    <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
      <img src={viteLogo} class="logo" alt="Vite Logo" width="202.25" height="200" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" width="174.35" height="200" />
    </a>
  </div>
  <h1>Hello {name}</h1>

  <Counter />

  <p>
    Check out <a href="https://github.com/sveltejs/kit#readme" target="_blank" rel="noreferrer">SvelteKit</a>, the official Svelte app framework powered by
    Vite!
  </p>

  <p class="read-the-docs">Click on the Vite and Svelte logos to learn more</p>
</main>

<style>
</style>
